function [fitresult, gof] = createFit(x0, y0)
%CREATEFIT(X0,Y0)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input: x0
%      Y Output: y0
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 09-Jun-2023 14:16:45


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( x0, y0 );

% Set up fittype and options.
ft = fittype( 'smoothingspline' );
opts = fitoptions( 'Method', 'SmoothingSpline' );
opts.SmoothingParam = 0.999813534625311;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'y0 vs. x0', 'untitled fit 1', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'x0', 'Interpreter', 'none' );
ylabel( 'y0', 'Interpreter', 'none' );
grid on


